### ISSUE TITLE
Recognition of the system "Twilight: 2000 - Core"

### ISSUE THREAD

**Issue by FatherJ-ct** [fantasycalendar/FoundryVTT-ItemPiles#154]
I would like to request that the foundry vtt system "Twilight: 2000 - Core" become a recognized system.

The items pile module sounds great and am interested to use, but myself and another GM (@Daniel@Spelkult.se on discord) were not able to get it to work. Though Daniel did mention it was working for him prior to v10.

For me, it did warn that the system was not recognized and I did not see Twilight 2000 as a supported system on the list. I am new to using foundry and the twilight system so am not sure what system specific settings should be used (I am not a coder). I assume a supported system would have those settings filled in.

I just installed item piles, tried to drag off  "field rations (10)" from a test player charater's sheet onto the battlemap and it flashed an error. Console shows the following:
Foundry VTT | Deleted Item with id [lGmC1WuDlrcY7ZPa] in parent Actor [GYa4ftrCueqjlcAw]
foundry.js:58721 Item Piles | A Default Item Pile has been added to your Actors list. You can configure the default look and behavior on it, or duplicate it to create different styles.
helpers.js:73 Item Piles | A Default Item Pile has been added to your Actors list. You can configure the default look and behavior on it, or duplicate it to create different styles.
foundry.js:747 Error: ActorT2K Model Validation Errors
[ActorT2K.type]: may not be a blank string
[Detected 2 packages: system:t2k4e, item-piles]
    at SchemaField._validateType (commons.js:4090:15)
    at SchemaField.validate (commons.js:3817:37)
    at ActorT2K.validate (commons.js:5470:35)
    at new DataModel (commons.js:5247:26)
    at new Document (commons.js:5786:3)
    at new BaseActor (commons.js:7133:3)
    at new ClientDocumentMixin (foundry.js:12996:5)
    at new Actor (foundry.js:16222:1)
    at new ActorT2K (t2k4e.js:15:5715)
    at ClientDatabaseBackend._preCreateDocumentArray (foundry.js:12478:15)
    at ClientDatabaseBackend._createDocuments (foundry.js:12414:33)
    at ClientDatabaseBackend.create (commons.js:6713:24)
    at async Actor.createDocuments (commons.js:6085:23)
    at async Actor.create (commons.js:6208:23)
    at async PrivateAPI._createItemPile (private-api.js:605:21)
    at async PrivateAPI._dropItems (private-api.js:562:22)
onError @ foundry.js:747
foundry.js:58721 ActorT2K Model Validation Errors
[ActorT2K.type]: may not be a blank string
[Detected 2 packages: system:t2k4e, item-piles]
fetch @ foundry.js:58721
private-api.js:612 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'update')
[Detected 1 package: item-piles]
    at PrivateAPI._createItemPile (private-api.js:612:25)
    at async PrivateAPI._dropItems (private-api.js:562:22)

As extra info. The twilight:2000 - core set is officially made by publisher Free league (Frea Ligan)
It states the foundry edition is by Stephane Van Cauwenberghe (stefouch) and also has a "Questions? info@frialigan.se"

**Comment by FatherJ-ct** [comment]
Also, this was discussed in free league's Twilight 2000 4E discord server's #referee-studio. https://discord.gg/gc622Fay

**Comment by Haxxer** [comment]
Please use the system request issue template. I do not use the system, so I don't know anything about it.
