### ISSUE TITLE
Cant Populate items

### ISSUE THREAD

**Issue by Axblade** [fantasycalendar/FoundryVTT-ItemPiles#232]
**Describe the bug**
Cant open populate Items

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'reduce')
[Detected 1 package: item-piles]
    at MerchantStore.updatePriceModifiers (merchant-store.js:101:68)
    at Array.<anonymous> (merchant-store.js:51:12)
    at Object.set (index.mjs:34:45)
    at Array.sliderinput1_value_binding (MerchantLeftPane.svelte:120:88)
    at sliderinput1_value_binding (MerchantLeftPane.svelte:113:71)
    at bind$1 (index.mjs:1923:13)
    at MerchantLeftPane.svelte:120:56
    at flush (index.mjs:1166:34)

**To Reproduce**
Click new token
Configure
Enable
Other Settings
Type Merchant
Update Item Pile

Select settings then attempt select populate

**Expected behavior**
Beable to set roll table and to roll items.

**Setup:**
V 10.291
5e 2.0.3 

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Running on the [Forge server.](https://www.foundryserver.com/)

**Comment by Haxxer** [comment]
I can't seem to reproduce your issue.

- What is the Item Piles version you are using?
- Does this happen every time for you?
- Have you tried to reset the system specific settings in the item piles module settings?

**Comment by Haxxer** [comment]
This should be fixed in 2.4.3
