### ISSUE TITLE
[BUG] - - Cannot open items from Compendiums while Items Piles is enabled

### ISSUE THREAD

**Issue by action-jay** [fantasycalendar/FoundryVTT-ItemPiles#369]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
Afteer upgrading to Foundry version 11, I'm unable to open items from within compendiums while Item Piles is enabled

**To Reproduce**

1. Open a compendium (actor, table, journal, item, doesn't seem to matter)
2. Click on any entry

**Expected behavior**
Normally the item would open for viewing or editing

**Screenshots**
No screenshot, but I do have console log output:

```
libWrapper-wrapper.js:669 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'get')
[Detected 2 packages: item-piles, lib-wrapper]
    at 🎁DocumentDirectory.prototype._onClickEntryName#item-piles (libwrapper.js:26:50)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁DocumentDirectory.prototype._onClickEntryName#0 (libWrapper-wrapper.js:189:20)
    at HTMLOListElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
foundry.js:5716 Foundry VTT | Rendering Compendium
libWrapper-wrapper.js:669 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'get')
[Detected 2 packages: item-piles, lib-wrapper]
    at 🎁DocumentDirectory.prototype._onClickEntryName#item-piles (libwrapper.js:26:50)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁DocumentDirectory.prototype._onClickEntryName#0 (libWrapper-wrapper.js:189:20)
    at HTMLOListElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

**Setup:**

- Foundry Version: 11.299
- System Version: DnD5e 2.2.1
- Item Piles Version: 2.6.13
- Browser & version: Foundry built-in

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
The functionality of Item Piles itself seems to be working well after the upgrade

**Comment by Haxxer** [comment]
Fixed in 2.6.14
