### ISSUE TITLE
[BUG] - [SYSTEM NAME] - Describe bug here

### ISSUE THREAD

**Issue by Theopholis** [fantasycalendar/FoundryVTT-ItemPiles#373]
**Have you tried to reset Item Piles' system settings?**
Yes 

**Describe the bug**
Players cannot open piles. The icon appears on the screen but cannot open it. If I give the players Assistant DM permissions, they can open. If I give them trusted player status and check all boxes allowing them the same permissions as an Assistant DM, it will not allow them to open the pile. Tested with just the basic required modules and same results. 
If I open it as DM and share the pile with players, it will open for them and they can interact with it.

**Expected behavior**
Players could open and interact with piles. 

**Setup:**

- Foundry Version: 11.299
- System Version: [e.g. DND5e 2.2.1
- Item Piles Version: 2.6.15
- Browser & version Tried in latest Chrome, Edge & Host

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**

**Comment by Haxxer** [comment]
No errors in the console?

**Comment by Theopholis** [comment]
I went to my console from on the players side and when I attempt to click on the chest, this is what shows up.

commons.js:2004 Error: event.data.origin is deprecated in favor of event.interactionData.origin.
Deprecated since Version 11
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:1993:19)
    at Xt.get (foundry.js:31582:25)
    at Canvas.canvasOnClickLeft (smartTarget.js:51:41)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Canvas.prototype._onClickLeft#0 (libWrapper-wrapper.js:189:20)
    at MouseInteractionManager.callback (foundry.js:31043:17)
    at #handleClickLeft (foundry.js:31230:15)
    at #handleMouseDown (foundry.js:31215:38)
    at Na.notifyListeners (earcut.js:128:75)
    at Na.notifyTarget (earcut.js:128:75)
    at Na.propagate (earcut.js:128:75)
    at Na.dispatchEvent (earcut.js:128:75)
    at Na.mapPointerDown (earcut.js:128:75)
    at Na.mapEvent (earcut.js:128:75)
    at yn.onPointerDown (earcut.js:128:75)
logCompatibilityWarning @ commons.js:2004
get @ foundry.js:31582
canvasOnClickLeft @ smartTarget.js:51
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Canvas.prototype._onClickLeft#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:31043
#handleClickLeft @ foundry.js:31230
#handleMouseDown @ foundry.js:31215
notifyListeners @ earcut.js:128
notifyTarget @ earcut.js:128
propagate @ earcut.js:128
dispatchEvent @ earcut.js:128
mapPointerDown @ earcut.js:128
mapEvent @ earcut.js:128
onPointerDown @ earcut.js:128
2hotkeys.js:73 Uncaught TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 1 package: item-piles]
    at hotkeys.js:73:65

**Comment by Theopholis** [comment]
Thanks for the fix. That was quick.
