### ISSUE TITLE
[BUG] - [Cyberpunk  Red] - Undefined error when dropping item from compendium onto scene

### ISSUE THREAD

**Issue by diwako** [fantasycalendar/FoundryVTT-ItemPiles#442]
**Have you tried to reset Item Piles' system settings?**
Yes

**Describe the bug**
When dragging an item out of the compendium, it errors out

**To Reproduce**

1. create new world or launch existing
2. have a scene
3. drag any item from compendium OR token/actor to scene
4. error in console

**Expected behavior**
A token with the contents of the dragged item is created on scene

**Screenshots**
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/assets/8259498/c30bc357-377c-4430-a4d9-7db1911474e1)

**Setup:**

- Foundry Version: 10.303
- System Version: Cyberpunk Red 0.87.6
- Item Piles Version: 2.7.10
- Browser & version Google Chrome 

**Active modules:**

- Item Piles
- libwrapper
- socketlib
- quick inserts

**Additional context**
Appears to unrelated to CPRED fixes
Errors in console

When launching world:
```log
utilities.js:166 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getItemTypesThatCanStack (utilities.js:166:34)
    at refreshItemTypesThatCanStack (utilities.js:160:3)
    at Object.onChange (settings.js:151:9)
    at Setting._onCreate (foundry.js:21329:55)
    at ClientDatabaseBackend.callback (foundry.js:12612:11)
    at foundry.js:12562:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:12562:33)
    at ClientDatabaseBackend._createDocuments (foundry.js:12468:17)
    at async Setting.createDocuments (commons.js:6110:23)
    at async Setting.create (commons.js:6233:23)
    at async ClientSettings.set (foundry.js:2872:14)
    at async applyDefaultSettings (settings.js:29:5)
    at async module.js:96:7
```

When dragging onto scene:
```log
Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getItemTypesThatCanStack (utilities.js:166:34)
    at canItemStack (pile-utilities.js:43:27)
    at PrivateAPI._dropItem (private-api.js:1763:9)
```

**Comment by Haxxer** [comment]
Fixed in 2.7.11
