### ISSUE TITLE
[BUG] - [PF1] - Cannot open merchant item pile sheet

### ISSUE THREAD

**Issue by guillaume-gc** [fantasycalendar/FoundryVTT-ItemPiles#444]
**Have you tried to reset Item Piles' system settings?**
Yes.

**Describe the bug**
When I double click on a merchant token as a player or as a GM, I have this error:
```
TypeError: An error occurred while rendering MerchantApp 155. Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getItemTypesThatCanStack (utilities.js:166:34)
    at canItemStack (pile-utilities.js:43:27)
    at PileMerchantItem.setupStores (pile-item.js:60:21)
    at PileMerchantItem.setupStores (merchant-store.js:328:11)
    at PileMerchantItem.setup (pile-item.js:37:10)
    at new PileBaseItem (pile-item.js:18:10)
    at new PileItem (pile-item.js:54:8)
    at new PileMerchantItem (merchant-store.js:325:1)
    at item-pile-store.js:184:18
    at Array.map (<anonymous>)
    at MerchantStore.setupSubscriptions (item-pile-store.js:183:45)
    at MerchantStore.setupSubscriptions (merchant-store.js:63:11)
    at MerchantStore.make (item-pile-store.js:83:11)
    at instance$x (merchant-app-shell.svelte:21:36)
    at init (index.mjs:2098:11)
    at new Merchant_app_shell (merchant-app-shell.svelte:103:55)
    at loadSvelteConfig (loadSvelteConfig.js:90:22)
    at MerchantApp._injectHTML (SvelteApplication.js:484:29)
    at MerchantApp._render (foundry.js:5131:12)
    at async MerchantApp._render (SvelteApplication.js:872:7)
```

Note: the same issue happens when I click on the NPC in the actor tab. This is a serious problem, as this prevents me to also access the actor "normal" sheet, so I need to either manually modify the actor sheet JSON file or delete and re-create it.

**To Reproduce**

1. Create a NPC.
2. Give at least one item to the NPC.
3. Set this NPC as a merchant using Item Piles.
4. Drop the NPC on a scene.
5. Double click on the NPC as a GM, or as a player near the NPC.
6. Nothing happens, and an error is displayed on the console.

**Expected behavior**
The merchant screen should open.

**Screenshots**
No screenshots provided.

**Setup:**

- Foundry Version: 10.303
- System Version: Pathfinder 1e 9.4
- Item Piles Version: 2.7.10
- Browser & version: Brave v1.57.57, Chromium: 116.0.5845.163

**Active modules:**

- Item Piles
- libwrapper
- socketlib

**Additional context**
Here is the actor sheet in an archive file: [fvtt-Actor-rufus-le-negociateur.zip](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/files/12505967/fvtt-Actor-rufus-le-negociateur.zip)

**Comment by Haxxer** [comment]
Fixed in 2.7.11
